spring:
  jpa:
    show-sql: true

dbencrypt:
  encryption-secret: local-secret-key-12345

---
spring:
  profiles: cloud

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

dbencrypt:
  encryption-secret: ${vcap.services.mycredhub.encryption-secret}
